spring:
  application:
    name: api_productos

  datasource:
    # Cambia el protocolo a mariadb
    url: jdbc:mariadb://localhost:3307/equipo
    username: root
    password: secreta
    # Usa el driver específico de MariaDB
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        # Usa el dialecto específico para MariaDB
        dialect: org.hibernate.dialect.MariaDBDialect